export type OpRisk = "low" | "medium" | "high" | "critical";
export type OpCategory = "flight" | "mission" | "dock" | "camera" | "safety";
export type OpBlockRule = "command_ready" | "online" | "gateway_online" | "none";
export type OpDeviceRole = "drone" | "gateway" | "any";

export interface OpDefinition {
  action: string;
  path: string;
  label: string;
  description: string;
  category: OpCategory;
  risk: OpRisk;
  blockRule: OpBlockRule;
  deviceRole: OpDeviceRole;
  requiresMissionId?: boolean;
  fh2Capability: string;
}

/** FlightHub 2–aligned command catalog (middleware audit + readiness gate). */
export const OPERATIONS_CATALOG: OpDefinition[] = [
  {
    action: "takeoff",
    path: "takeoff",
    label: "Takeoff",
    description: "Launch aircraft from ground or dock.",
    category: "flight",
    risk: "high",
    blockRule: "command_ready",
    deviceRole: "drone",
    fh2Capability: "Remote Control — takeoff",
  },
  {
    action: "land",
    path: "land",
    label: "Land",
    description: "Land at current position.",
    category: "flight",
    risk: "high",
    blockRule: "command_ready",
    deviceRole: "drone",
    fh2Capability: "Remote Control — land",
  },
  {
    action: "hover",
    path: "hover",
    label: "Hover / Hold",
    description: "Hold position and altitude (stop forward motion).",
    category: "flight",
    risk: "medium",
    blockRule: "command_ready",
    deviceRole: "drone",
    fh2Capability: "Remote Control — hover",
  },
  {
    action: "rth",
    path: "rth",
    label: "Return to Home",
    description: "Fly back to home point and land.",
    category: "flight",
    risk: "high",
    blockRule: "command_ready",
    deviceRole: "drone",
    fh2Capability: "Remote Control — return home",
  },
  {
    action: "emergency_stop",
    path: "emergency/stop",
    label: "Emergency Stop",
    description: "Immediate motor stop / flight termination (use only in emergency).",
    category: "safety",
    risk: "critical",
    blockRule: "none",
    deviceRole: "drone",
    fh2Capability: "Remote Control — emergency stop",
  },
  {
    action: "mission_start",
    path: "mission/start",
    label: "Mission Start",
    description: "Start selected wayline / flight task.",
    category: "mission",
    risk: "high",
    blockRule: "online",
    deviceRole: "drone",
    requiresMissionId: true,
    fh2Capability: "Task Management — start mission",
  },
  {
    action: "mission_pause",
    path: "mission/pause",
    label: "Mission Pause",
    description: "Pause active wayline execution.",
    category: "mission",
    risk: "medium",
    blockRule: "command_ready",
    deviceRole: "drone",
    fh2Capability: "Task Management — pause",
  },
  {
    action: "mission_resume",
    path: "mission/resume",
    label: "Mission Resume",
    description: "Resume paused wayline.",
    category: "mission",
    risk: "medium",
    blockRule: "command_ready",
    deviceRole: "drone",
    fh2Capability: "Task Management — resume",
  },
  {
    action: "mission_cancel",
    path: "mission/cancel",
    label: "Mission Cancel",
    description: "Abort mission and hold or RTH per aircraft policy.",
    category: "mission",
    risk: "critical",
    blockRule: "command_ready",
    deviceRole: "drone",
    fh2Capability: "Task Management — cancel",
  },
  {
    action: "mission_recover",
    path: "mission/recover",
    label: "Mission Recover",
    description: "Recover interrupted mission (FH2 resume-from-breakpoint).",
    category: "mission",
    risk: "high",
    blockRule: "online",
    deviceRole: "drone",
    fh2Capability: "Task Management — recover",
  },
  {
    action: "mission_stop",
    path: "mission/stop",
    label: "End Mission",
    description: "Stop mission without deleting task record.",
    category: "mission",
    risk: "high",
    blockRule: "command_ready",
    deviceRole: "drone",
    fh2Capability: "Task Management — stop",
  },
  {
    action: "dock_cover_open",
    path: "dock/cover/open",
    label: "Open Dock Cover",
    description: "Open dock protective cover before launch.",
    category: "dock",
    risk: "medium",
    blockRule: "gateway_online",
    deviceRole: "gateway",
    fh2Capability: "Dock — cover open",
  },
  {
    action: "dock_cover_close",
    path: "dock/cover/close",
    label: "Close Dock Cover",
    description: "Close dock cover after landing.",
    category: "dock",
    risk: "medium",
    blockRule: "gateway_online",
    deviceRole: "gateway",
    fh2Capability: "Dock — cover close",
  },
  {
    action: "dock_drone_out",
    path: "dock/drone/out",
    label: "Drone Out (Launch)",
    description: "Release aircraft from dock for takeoff sequence.",
    category: "dock",
    risk: "high",
    blockRule: "gateway_online",
    deviceRole: "gateway",
    fh2Capability: "Dock — drone out",
  },
  {
    action: "dock_drone_in",
    path: "dock/drone/in",
    label: "Drone In (Recover)",
    description: "Recall aircraft into dock bay.",
    category: "dock",
    risk: "high",
    blockRule: "gateway_online",
    deviceRole: "gateway",
    fh2Capability: "Dock — drone in",
  },
  {
    action: "dock_rth",
    path: "dock/rth",
    label: "Dock Return Home",
    description: "Command aircraft to return to paired dock.",
    category: "dock",
    risk: "high",
    blockRule: "online",
    deviceRole: "gateway",
    fh2Capability: "Dock — return to dock",
  },
  {
    action: "dock_charge_start",
    path: "dock/charge/start",
    label: "Start Charging",
    description: "Enable dock battery charging cycle.",
    category: "dock",
    risk: "low",
    blockRule: "gateway_online",
    deviceRole: "gateway",
    fh2Capability: "Dock — charging",
  },
  {
    action: "dock_charge_stop",
    path: "dock/charge/stop",
    label: "Stop Charging",
    description: "Stop dock charging cycle.",
    category: "dock",
    risk: "low",
    blockRule: "gateway_online",
    deviceRole: "gateway",
    fh2Capability: "Dock — charging",
  },
  {
    action: "camera_photo",
    path: "camera/photo",
    label: "Take Photo",
    description: "Trigger single photo capture on live payload.",
    category: "camera",
    risk: "low",
    blockRule: "command_ready",
    deviceRole: "drone",
    fh2Capability: "Camera — photo",
  },
  {
    action: "camera_record_start",
    path: "camera/record/start",
    label: "Start Recording",
    description: "Start video recording on selected payload.",
    category: "camera",
    risk: "low",
    blockRule: "command_ready",
    deviceRole: "drone",
    fh2Capability: "Camera — record start",
  },
  {
    action: "camera_record_stop",
    path: "camera/record/stop",
    label: "Stop Recording",
    description: "Stop video recording.",
    category: "camera",
    risk: "low",
    blockRule: "command_ready",
    deviceRole: "drone",
    fh2Capability: "Camera — record stop",
  },
  {
    action: "camera_gimbal_reset",
    path: "camera/gimbal/reset",
    label: "Gimbal Reset",
    description: "Reset gimbal to default nadir / forward.",
    category: "camera",
    risk: "low",
    blockRule: "command_ready",
    deviceRole: "drone",
    fh2Capability: "Gimbal — reset",
  },
  {
    action: "camera_switch",
    path: "camera/switch",
    label: "Switch Camera / Lens",
    description: "Switch active payload camera or lens profile.",
    category: "camera",
    risk: "low",
    blockRule: "command_ready",
    deviceRole: "drone",
    fh2Capability: "Camera — switch",
  },
  {
    action: "link_refresh",
    path: "safety/link-refresh",
    label: "Refresh Control Link",
    description: "Request FH2 control channel / DRC link refresh.",
    category: "safety",
    risk: "low",
    blockRule: "none",
    deviceRole: "any",
    fh2Capability: "Remote Control — link refresh",
  },
  {
    action: "flight_authority_request",
    path: "safety/flight-authority",
    label: "Request Flight Authority",
    description: "Request control authority when shared with another operator.",
    category: "safety",
    risk: "medium",
    blockRule: "online",
    deviceRole: "any",
    fh2Capability: "Remote Control — authority",
  },
];

export const OP_CATEGORIES: { id: OpCategory; label: string; hint: string }[] = [
  { id: "flight", label: "Flight Control", hint: "Takeoff, land, hover, RTH" },
  { id: "mission", label: "Mission / Wayline", hint: "Start, pause, cancel, recover" },
  { id: "dock", label: "Dock & Ground Station", hint: "Cover, launch, recover, charge" },
  { id: "camera", label: "Camera & Payload", hint: "Photo, video, gimbal" },
  { id: "safety", label: "Safety & Link", hint: "Emergency, authority, link" },
];

export function getOpByPath(path: string): OpDefinition | undefined {
  return OPERATIONS_CATALOG.find((o) => o.path === path);
}
